# Production overrides for docker-compose.yml
version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  redis:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  airflow-webserver:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_URL}
      AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW_CELERY_BROKER_URL}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
      AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE: 'false'
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    volumes:
      - airflow_logs:/opt/airflow/logs

  airflow-scheduler:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_URL}
      AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW_CELERY_BROKER_URL}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    volumes:
      - airflow_logs:/opt/airflow/logs

  airflow-worker:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_URL}
      AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW_CELERY_BROKER_URL}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    volumes:
      - airflow_logs:/opt/airflow/logs

  dbt:
    environment:
      DBT_TARGET: prod
      DBT_SNOWFLAKE_ACCOUNT: ${DBT_SNOWFLAKE_ACCOUNT}
      DBT_SNOWFLAKE_USER: ${DBT_SNOWFLAKE_USER}
      DBT_SNOWFLAKE_PASSWORD: ${DBT_SNOWFLAKE_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  ingestion-service:
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  processing-service:
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  monitoring-service:
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

volumes:
  postgres_prod_data:
  airflow_logs: